# Generated by Django 3.2.5 on 2021-07-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_rename_cases_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
