# Generated by Django 3.2.5 on 2021-07-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='National',
            new_name='Cases',
        ),
    ]
