# Generated by Django 3.2.5 on 2021-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0006_alter_data_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
