# Generated by Django 3.2.5 on 2021-07-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_past', '0002_rename_statepast_cases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cases',
            new_name='Data',
        ),
    ]
